"""API 사용량 로그 테이블 추가

Revision ID: 8a94c3a48e67
Revises: d62ec2df6fc2
Create Date: 2026-09-07 21:45:07.589284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8a94c3a48e67'
down_revision: Union[str, None] = 'd62ec2df6fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('text_tokens', sa.Integer(), nullable=False),
    sa.Column('image_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_text_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_image_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_code_id'), 'api_usage_logs', ['code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_usage_logs_code_id'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    # ### end Alembic commands ###
