"""카드 결정 여부 컬럼 추가

Revision ID: d62ec2df6fc2
Revises: edb239063726
Create Date: 2026-09-07 00:25:20.859757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd62ec2df6fc2'
down_revision: Union[str, None] = 'edb239063726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('decided', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'decided')
    # ### end Alembic commands ###
