"""초기 스키마

Revision ID: edb239063726
Revises: 
Create Date: 2026-09-07 00:07:37.261975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'edb239063726'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # sessions <-> images 사이의 순환 참조 때문에 sessions를 이미지 FK 없이 먼저
    # 만들고, images 생성 후 ALTER TABLE로 FK를 붙인다.
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.String(length=32), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_turns', sa.Integer(), nullable=False),
    sa.Column('story_time', sa.String(length=5), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('presets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('portrait_image_id', sa.UUID(), nullable=True),
    sa.Column('portrait_retry_count', sa.Integer(), nullable=False),
    sa.Column('portrait_confirmed', sa.Boolean(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('closeness', sa.Integer(), nullable=False),
    sa.Column('tension', sa.Integer(), nullable=False),
    sa.Column('help_status', sa.String(length=32), nullable=False),
    sa.Column('book_owner', sa.String(length=16), nullable=False),
    sa.Column('bookmark_owner', sa.String(length=16), nullable=False),
    sa.Column('future_plan', sa.Text(), nullable=True),
    sa.Column('future_plan_accepted', sa.Boolean(), nullable=False),
    sa.Column('contact_exchanged', sa.Boolean(), nullable=False),
    sa.Column('player_present', sa.Boolean(), nullable=False),
    sa.Column('door_locked', sa.Boolean(), nullable=False),
    sa.Column('ended_early', sa.Boolean(), nullable=False),
    sa.Column('ending_title', sa.Text(), nullable=True),
    sa.Column('ending_body', sa.Text(), nullable=True),
    sa.Column('ending_unresolved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ending_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ending_image_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_id', 'index', name='uq_session_code_index')
    )
    op.create_index(op.f('ix_sessions_code_id'), 'sessions', ['code_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_sessions_portrait_image_id', 'sessions', 'images', ['portrait_image_id'], ['id'])
    op.create_foreign_key('fk_sessions_ending_image_id', 'sessions', 'images', ['ending_image_id'], ['id'])
    op.create_table('card',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('written', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=16), nullable=True),
    sa.Column('owner', sa.String(length=16), nullable=False),
    sa.Column('decided_turn', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('image_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'kind', 'scene_id', name='uq_image_job_slot')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('scene_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'event_key', name='uq_scene_event_once')
    )
    op.create_table('confirmed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmed_events')
    op.drop_table('scene_events')
    op.drop_table('requests')
    op.drop_table('messages')
    op.drop_table('image_jobs')
    op.drop_table('card')
    op.drop_constraint('fk_sessions_ending_image_id', 'sessions', type_='foreignkey')
    op.drop_constraint('fk_sessions_portrait_image_id', 'sessions', type_='foreignkey')
    op.drop_table('images')
    op.drop_index(op.f('ix_sessions_code_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
