import { useLayoutEffect, useRef } from 'react';
import type { Ending, Message } from '../types/api';
import { SceneImage } from '../components/SceneImage';
import { EvidenceTrail } from '../components/EvidenceTrail';
import { Icon } from '../components/Icon';
import s from '../App.module.css';
export function EndingScreen({ ending, messages, storyTime, index, onConversation, onQuote, onSessions, onNew, onRetryImage, retryBusy, imageError, savedScroll, onScroll }: {
  ending: Ending; messages: Message[]; storyTime: string; index: number; onConversation: () => void; onQuote: (id: string) => void; onSessions: () => void; onNew: () => void; onRetryImage: () => void; retryBusy: boolean; imageError: string; savedScroll: number; onScroll: (top: number) => void;
}) {
  const root = useRef<HTMLDivElement>(null);
  useLayoutEffect(() => { if (root.current) root.current.scrollTop = savedScroll; }, []);
  return <main className={s.endingLayout}><aside className={s.imageColumn}><SceneImage url={ending.image.url} label="이 이야기의 마지막 그림" generating={ending.image.status === 'generating' || retryBusy} failed={ending.image.status === 'failed' || ending.image.status === 'rejected'} onRetry={onRetryImage} busy={retryBusy}/><div className={s.imageCaption}><span>{index}번째 이야기의 마지막 장면</span><p>{storyTime} · 사이책방</p></div>{imageError && <p className={s.error} role="alert">{imageError} <button className={s.textButton} onClick={onRetryImage} disabled={retryBusy}>그림 다시 만들기</button></p>}</aside><div ref={root} className={s.endingScroll} onScroll={event => onScroll(event.currentTarget.scrollTop)} tabIndex={0} aria-label="결말과 이 결말에 남은 대화"><article className={s.endingArticle}><header className={s.endingTitle}><span className={s.eyebrow}>마지막 페이지 · {index}번째 이야기</span><h1>{ending.title}</h1><span className={s.endingTime}>{storyTime}, 사이책방에서</span></header><div className={s.endingBody}>{ending.body.split(/\n\s*\n/).map((paragraph, i) => <p key={i}>{paragraph}</p>)}</div><section className={s.writtenCard}><span className={s.noteTab}/><span className={s.eyebrow}>{ending.card.written ? ending.card.author === 'player' ? '당신이 카드에 남긴 문장' : '서윤이 카드에 남긴 문장' : '그날의 카드'}</span>{ending.card.written ? <blockquote>{ending.card.text}</blockquote> : <p className={s.blankCard}>카드는 빈 채로 남았다.</p>}<span className={s.cardSignature}>{ending.card.written ? ending.card.author === 'player' ? '당신으로부터' : '서윤으로부터' : '쓰지 않은 마음까지, 그대로.'}</span></section><EvidenceTrail evidence={ending.evidence} messages={messages} scrollRoot={root} onQuote={onQuote}/><section className={s.unresolved}><h2>아직 남은 것</h2>{ending.unresolved.map((text, i) => <p key={i}>{text}</p>)}</section><footer className={s.endingActions}><div><button className={s.secondary} onClick={onConversation}><Icon name="book" size={17}/> 대화 다시 보기</button><button className={s.textButton} onClick={onSessions}>다른 회차 보기</button></div><div className={s.newStoryEnd}><button className={s.primary} onClick={onNew}>새 이야기 시작하기<Icon name="arrow" size={17}/></button><p>같은 시작에서도 다른 결말이 나옵니다.</p></div><span className={s.endingColophon}>마지막 책갈피</span></footer></article></div></main>;
}
